from typing import Any, List, Union

class CommonBase:
    def external_command(self, cmd: Any, success_code: Any=..., do_combine: Any=..., return_binary: Any=..., environment: Any=..., wd: Any=..., do_discard_stderr: Any=...) -> Union[List[str], str, bytes]: ...
    def rows_to_dict(self, rows: Any, lc: bool = ...): ...
