import svn.common
from typing import Any, Optional

class RemoteClient(svn.common.CommonClient):
    def __init__(self, url: Any, *args: Any, **kwargs: Any) -> None: ...
    def checkout(self, path: Any, revision: Optional[Any] = ...) -> None: ...
    def remove(self, rel_path: Any, message: Any, do_force: bool = ...) -> None: ...
