def temp_path() -> None: ...
def temp_repo() -> None: ...
def temp_checkout() -> None: ...
def temp_common() -> None: ...
def populate_bigger_file_changes1() -> None: ...
def populate_bigger_file_change1(): ...
